name: Compile LevelDB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile for linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          rm -rf build-linux || true
          rm -rf lib-linux || true
          mkdir build-linux && mkdir lib-linux && cd build-linux
          cmake -DCMAKE_BUILD_TYPE=Release ../leveldb && cmake --build .
          tree
          cp libleveldb.a ../lib-linux


      - name: Install MinGW
        if: matrix.os == 'windows-latest'
        run: |
          choco install mingw -y

      - name: Compile for windows
        if: matrix.os == 'windows-latest'
        run: |
          $env:Path += ";C:\tools\mingw\bin"
          $env:Path += ";C:\tools\mingw\msys\1.0\bin"
          Remove-Item -LiteralPath "build-windows" -Force -Recurse -ErrorAction SilentlyContinue
          Remove-Item -LiteralPath "lib-windows" -Force -Recurse -ErrorAction SilentlyContinue
          mkdir build-windows
          mkdir lib-windows
          cd build-windows
          cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release ../leveldb
          mingw32-make
          tree /F
          copy libleveldb.a ../lib-windows

#          $env:Path += ";C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE"
#          cmake -G "Visual Studio 17 2022" -A x64 ../leveldb
#          devenv /build Release leveldb.sln

      - name: Commit changes linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main || true
          git add ./lib-linux
          git commit -m "compile leveldb" || true
          git push || true

      - name: Commit changes windows
        if: matrix.os == 'windows-latest'
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull origin main
          git add ./lib-windows
          git commit -m "compile leveldb"
          git push
